config/routes.rb
Rails.application.routes.draw do
  root 'home#index', as: 'root'
  get '/about-us' => 'about#index', as: 'about'
  get '/other' => 'other#index', as: 'other'
  get '/sign-up' => 'auth#register_form', as: 'register_form'
  post '/sign-up' => 'auth#registration', as: 'registration'
  get '/sign-in' => 'auth#login_form', as: 'login_form'
  post '/sign-in' => 'auth#login', as: 'login'
  delete '/logout' => 'auth#logout', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/auth.rb
# frozen_string_literal: true

class Auth < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
# name:string
# email:string
# password_digest:string
#
# password:string virtual
# password_confirmation:string virtual

class User < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3}
  validates :email, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9]+[\w\-.]*@[a-zA-Z]+\.[a-zA-Z]+\z/, message: "Invalid email address" }
  validates :password, presence: true, length: {minimum: 8}
  validates :password_confirmation, presence: true
  validate  :password_match

  def password_match
    if password.present? && password_confirmation.present? && password != password_confirmation
      errors.add(:password_confirmation, "does not match password")
    end
  end

  has_secure_password
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def index
    #
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_auth_user
  def set_auth_user
    if session[:user_id]
      Auth.user = User.find_by(id: session[:user_id])
    end
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  # Viewing registration form
  def register_form
    @user = User.new
  end

  # Creating user
  def registration
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Registration successfully completed!"
      redirect_to root_path
    else
      render :register_form, status: :unprocessable_entity
    end
  end

  # Login Form
  def login_form
  end

  # Login
  def login
    @user = User.find_by(email: params[:email])
    if @user.present? && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = "Login successful!"
      redirect_to root_path
    end
  end

  # Logout
  def logout
    session[:user_id] = nil
    flash[:success] = "Logout successful!"
    redirect_to root_path
  end

  #Sanitizing form data
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/other_controller.rb
class OtherController < ApplicationController
  def index
    #
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/views/about/index.html.erb
<h1>About</h1>

app/views/home/index.html.erb
<h1>Home</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>StudentManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/other/index.html.erb
<h1>Other</h1>

app/views/shared/_flash.html.erb
<% if flash[:success].present? %>
  <div class="alert alert-success" role="alert">
    <%= flash[:success] %>
  </div>
<% end %>
<%# if flash[:alert] %>
<!--  <div class="alert alert-danger" role="alert">-->
    <%#= flash[:alert] %>
<!--  </div>-->
<%# end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%=link_to "Other", other_path, class: "nav-link" %>
        </li>

        <% unless Auth.user %>
        <li class="nav-item">
          <%=link_to "Sign Up", register_form_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%=link_to "Sign in", login_form_path, class: "nav-link" %>
        </li>
        <%  end %>
        <% if Auth.user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= Auth.user.name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="margin-left: -61px;">
              <a class="dropdown-item" href="#">
                <%= Auth.user.name %>
              </a>
              <a class="dropdown-item" href="#">
                <%= Auth.user.email %>
              </a>

              <div class="dropdown-divider"></div>
              <%=button_to "logout", logout_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>